[build-system]
requires = [
    "setuptools==75.8.1",
    "setuptools_scm >= 8.0.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "sample.module_under"
version = "1"

[tool.setuptools.packages.find]
where = ["src"]